# Generated by Django 2.2.5 on 2020-02-15 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailphotovoter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name='entryimage',
            name='author',
        ),
        migrations.RemoveField(
            model_name='entryimage',
            name='email',
        ),
        migrations.AddField(
            model_name='competition',
            name='entries_in_rating',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='competition',
            name='entries_per_person',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='entryimage',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='wagtailphotovoter.EntryUser'),
        ),
    ]
