# Generated by Django 3.0.3 on 2020-03-03 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailphotovoter', '0003_votes_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='entryimage',
            name='vote_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ImageVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_votes', to='wagtailphotovoter.EntryImage')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_votes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
