# Generated by Django 3.0.3 on 2020-03-04 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailphotovoter', '0004_auto_20200303_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='allow_same_points',
            field=models.BooleanField(default=False, help_text="Not working, don't enable"),
        ),
    ]
