# Generated by Django 3.1.7 on 2021-02-24 20:56

from django.db import migrations, models
import exiffield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailphotovoter', '0006_historicalvotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='entryimage',
            name='exif',
            field=exiffield.fields.ExifField(default={}, editable=False),
        ),
        migrations.AddField(
            model_name='entryimage',
            name='taken',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
