# Generated by Django 4.1.5 on 2023-01-25 18:31

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailphotovoter', '0007_auto_20210224_2256'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalvotes',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical votes', 'verbose_name_plural': 'historical votess'},
        ),
        migrations.AddField(
            model_name='competition',
            name='votinghelp',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='allow_same_points',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='entryimage',
            name='file_hash',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=40),
        ),
        migrations.AlterField(
            model_name='historicalvotes',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
